### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by deecodameeko** [arunisrael/angularjs-google-places#11]
Hello,

It'd be great if we could get the optional keyword parameter. I didn't see it specified in your defaults. I tried using it before looking at your code and it gave me no results.

Cheers

**Comment by deecodameeko** [comment]
I realized it doesn't take a list of keywords and that google places won't take multiple keyword query strings which is a bummer. Have dealt and worked around this limitation.

**Comment by deecodameeko** [comment]
It's actually a bug in google places. You can't have spaces in your keywords. Closing...

**Comment by ghost** [comment]
HI,
 I have been trying to use keywords with no success. I have a single key word with no spaces, but it makes no effect on the search. Can you suggest how to use keywords? I have been using keywords: 'keyword',  I tried keywords: ['keyword'],  I also tried using query: but no luck.
